# Generated by Django 4.1 on 2022-09-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='language',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='language',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='language',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='language',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='language',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='language',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='shopproduct',
            old_name='language',
            new_name='languages',
        ),
    ]
