# Generated by Django 4.1 on 2022-09-09 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220908_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_shop', to='products.category'),
        ),
    ]
