# Generated by Django 4.1 on 2022-09-08 09:38
import json

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    child_objects = []
    f = open('apps/common/fixtures/categories.json', encoding='utf-8')
    data = json.load(f)
    for key, value in data.items():
        parent = Category.objects.create(title=key)
        for item in value:
            child_objects.append(Category(title=item, parent=parent))

    Category.objects.bulk_create(child_objects, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_remove_comment_email_remove_comment_username_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_categories)
    ]
