# Generated by Django 4.1 on 2022-09-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shopproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='slug',
            field=models.SlugField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='slug',
            field=models.SlugField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='slug',
            field=models.SlugField(max_length=40, null=True),
        ),
    ]
