# Generated by Django 4.1 on 2022-09-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_brand_options_product_verified_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductShop',
            new_name='ShopProduct',
        ),
    ]
