# Generated by Django 4.1 on 2022-10-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_shopproduct_options'),
        ('products', '0008_alter_shopproduct_label'),
    ]

    operations = [
    ]
