# Generated by Django 4.1 on 2022-10-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_merge_20221003_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'verbose_name': 'Shop product', 'verbose_name_plural': 'Shop products'},
        ),
    ]
