json_first = [('add', '', [('foxmart-adata-uv220-8-gb-usb-2-0-gray-belyi', {'price': 89.0, 'available': True}),
                           ('foxmart-samsung-bar-plus-muf-32be3-apc-32-gb-serebristyi',
                            {'price': 299.0, 'available': True}),
                           (
                           'foxmart-transcend-jetflash-790-32-gb-usb-3-0-chernyi', {'price': 219.0, 'available': True}),
                           ('foxmart-transcend-jetflash-890-32-gb-usb-3-1-metal-serebristyi',
                            {'price': 359.0, 'available': True}),
                           (
                           'foxmart-transcend-jetflash-590-16-gb-usb-2-0-chernyi', {'price': 159.0, 'available': True}),
                           ('foxmart-adata-uv150-64-gb-usb-3-0-krasnyi', {'price': 229.0, 'available': True}),
                           (
                           'foxmart-transcend-jetflash-700-32-gb-usb-3-0-chernyi', {'price': 219.0, 'available': True}),
                           ('foxmart-transcend-jetflash-700-128-gb-chernyi', {'price': 569.0, 'available': True}),
                           (
                           'foxmart-transcend-jetflash-350-32-gb-usb-2-0-chernyi', {'price': 189.0, 'available': True}),
                           (
                           'foxmart-transcend-jetflash-350-16-gb-usb-2-0-chernyi', {'price': 159.0, 'available': True}),
                           ('foxmart-adata-c008-8-gb-usb-2-0-chernyi-krasnyi', {'price': 49.0, 'available': True}),
                           (
                           'foxmart-transcend-jetflash-700-64-gb-usb-3-0-chernyi', {'price': 259.0, 'available': True}),
                           ('foxmart-adata-uv150-32-gb-usb-3-0-chernyi', {'price': 189.0, 'available': True}),
                           ('foxmart-transcend-jetflash-730-128-gb-usb-3-0-belyi', {'price': 569.0, 'available': True}),
                           ('foxmart-apacer-ah333-32-gb-usb-2-0-belyi', {'price': 159.0, 'available': True}),
                           ('foxmart-transcend-jetflash-350-8-gb-chernyi', {'price': 149.0, 'available': True}),
                           ('foxmart-adata-uv150-64-gb-usb-3-0-chernyi', {'price': 229.0, 'available': True}),
                           ('foxmart-transcend-jetflash-790-64-gb-usb-3-0-belyi', {'price': 299.0, 'available': True}),
                           (
                           'foxmart-transcend-jetflash-750-32-gb-usb-2-0-chernyi', {'price': 399.0, 'available': True}),
                           ('foxmart-adata-uv150-16-gb-usb-3-0-krasnyi', {'price': 159.0, 'available': True}),
                           ('foxmart-apacer-ah360-16-gb-usb-3-1-dark-metal-chernyi',
                            {'price': 149.0, 'available': True}),
                           ('foxmart-apacer-ah333-16-gb-usb-2-0-chernyi', {'price': 139.0, 'available': True}),
                           ('foxmart-transcend-jetflash-710s-32-gb-usb-3-0-serebristyi',
                            {'price': 299.0, 'available': True}),
                           ('foxmart-transcend-jetflash-890-64-gb-usb-3-1-metal-serebristyi',
                            {'price': 519.0, 'available': True}),
                           ('foxmart-transcend-jetflash-730-64-gb-usb-3-0-belyi', {'price': 289.0, 'available': True}),
                           ('foxmart-transcend-jetflash-710s-64-gb-usb-3-0-serebristyi',
                            {'price': 449.0, 'available': True}),
                           ('foxmart-apacer-ah111-32-gb-usb-2-0-crystal-seryi', {'price': 189.0, 'available': True}), (
                               'foxmart-samsung-bar-plus-muf-32be3-apc-64-gb-usb-3-1-metal-chernyi',
                               {'price': 349.0, 'available': True}),
                           ('foxmart-adata-uv150-128-gb-usb-3-0-chernyi', {'price': 459.0, 'available': True}),
                           ('foxmart-adata-uv150-16-gb-usb-3-0-chernyi', {'price': 159.0, 'available': True}), (
                               'foxmart-samsung-bar-plus-muf-32be3-apc-32-gb-usb-3-1-metal-chernyi',
                               {'price': 299.0, 'available': True}),
                           ('foxmart-apacer-ah360-32-gb-usb-3-1-metal-chernyi', {'price': 189.0, 'available': True}),
                           (
                           'foxmart-transcend-jetflash-750-16-gb-usb-2-0-chernyi', {'price': 299.0, 'available': True}),
                           ('foxmart-transcend-jetflash-730-32-gb-usb-3-0-belyi', {'price': 239.0, 'available': True}),
                           (
                           'foxmart-transcend-jetflash-790-16-gb-usb-3-0-chernyi', {'price': 179.0, 'available': True}),
                           (
                           'foxmart-transcend-jetflash-700-16-gb-usb-3-0-chernyi', {'price': 189.0, 'available': True}),
                           ('foxmart-apacer-ah333-16-gb-usb-2-0-belyi', {'price': 139.0, 'available': True}),
                           ('foxmart-samsung-bar-plus-muf-32be3-apc-64-gb-serebristyi',
                            {'price': 349.0, 'available': True}),
                           (
                           'foxmart-transcend-jetflash-790-64-gb-usb-3-0-chernyi', {'price': 299.0, 'available': True}),
                           ('foxmart-apacer-ah111-32-gb-usb-2-0-seryi-sinii', {'price': 189.0, 'available': True}),
                           ('foxmart-apacer-ah333-32-gb-usb-2-0-chernyi', {'price': 159.0, 'available': True}),
                           ('foxmart-adata-uv150-32-gb-usb-3-0-krasnyi', {'price': 189.0, 'available': True}),
                           ('foxmart-kingston-data-travel-se9-g2-64-gb-usb-3-0-serebristyi',
                            {'price': 359.0, 'available': True}),
                           ('foxmart-apacer-ah359-64-gb-usb-3-1-chernyi-sinii', {'price': 259.0, 'available': True}),
                           ('foxmart-transcend-jetflash-790-32-gb-usb-3-0-white', {'price': 219.0, 'available': True}),
                           ('foxmart-apacer-ah360-64-gb-usb-3-1-black-nickel-chernyi',
                            {'price': 249.0, 'available': True}),
                           ('foxmart-transcend-jetflash-710s-128-gb-usb-3-0-serebristyi',
                            {'price': 699.0, 'available': True}),
                           ('foxmart-kingston-datatravel-70-32-gb-usb-3-2-gen-1-chernyi',
                            {'price': 149.0, 'available': True}),
                           ('foxmart-transcend-jetflash-890-128-gb-usb-3-1-metal-serebristyi',
                            {'price': 699.0, 'available': True}),
                           (
                           'foxmart-samsung-duo-plus-64-gb-usb-3-1-chernyi-seryi', {'price': 529.0, 'available': True}),
                           ('foxmart-kingston-datatravel-70-128-gb-usb-3-2-gen-1-chernyi',
                            {'price': 469.0, 'available': True}), (
                               'foxmart-samsung-bar-plus-muf-32be3-apc-256-gb-usb-3-1-metal-serebristyi',
                               {'price': 1299.0, 'available': True}),
                           ('foxmart-kingston-data-travel-se9-g2-128-gb-usb-3-0-serebristyi',
                            {'price': 559.0, 'available': True}), (
                               'foxmart-samsung-bar-plus-muf-32be3-apc-256-gb-usb-3-1-metal-seryi',
                               {'price': 1299.0, 'available': True}),
                           ('foxmart-kingston-datatravel-70-64-gb-usb-3-2-gen-1-chernyi',
                            {'price': 249.0, 'available': True}),
                           (
                           'foxmart-samsung-duo-plus-32-gb-usb-3-1-chernyi-seryi', {'price': 419.0, 'available': True}),
                           ('foxmart-samsung-duo-plus-256-gb-usb-3-1-chernyi-seryi',
                            {'price': 1449.0, 'available': True}),
                           ('foxmart-transcend-jet-flash-920-128-gb-seryi', {'price': 899.0, 'available': True}),
                           ('foxmart-kingston-dtmc3-64-gb-serebristyi', {'price': 439.0, 'available': True}),
                           ('foxmart-transcend-jetflash-370-32-gb-belyi', {'price': 189.0, 'available': True}),
                           ('foxmart-adata-uv350-32-gb-serebristyi', {'price': 169.0, 'available': True}),
                           ('foxmart-adata-uv350-64-gb-serebristyi', {'price': 229.0, 'available': True}),
                           ('foxmart-samsung-fit-plus-256-gb-chernyi', {'price': 1299.0, 'available': True}),
                           ('foxmart-kingston-dtmc3-128-gb-serebristyi', {'price': 669.0, 'available': True}),
                           ('foxmart-transcend-jet-flash-920-512-gb-seryi', {'price': 2299.0, 'available': True}),
                           ('foxmart-transcend-jet-flash-920-256-gb-seryi', {'price': 1299.0, 'available': True}),
                           ('foxmart-kingston-dtmc3-32-gb-serebristyi', {'price': 319.0, 'available': True}),
                           ('foxmart-adata-uv350-128-gb-serebristyi', {'price': 399.0, 'available': True}),
                           ('foxmart-transcend-jetflash-780-16-gb-usb-3-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-blaze-b02-16-gb-usb-3-0-chernyi',
                            {'price': 129.0, 'available': False}),
                           (
                           'foxmart-silicon-power-ultima-02-16-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-780-8-gb-usb-3-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-goldkey-usb-flash-8-gb-chernyi-zolotoi', {'price': 0.0, 'available': False}),
                           ('foxmart-pqi-u819l-8-gb-usb-2-0-chernyi', {'price': 89.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-02-8-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-300-16-gb-usb-2-0-purple-chernyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-touch-t30-8-gb-usb-2-0-rubber-korichnevyi',
                            {'price': 99.0, 'available': False}),
                           ('foxmart-apacer-ah326-16-gb-usb-2-0-chernyi', {'price': 79.0, 'available': False}),
                           ('foxmart-apacer-ah115-16-gb-usb-2-0-serebristyi', {'price': 139.0, 'available': False}),
                           ('foxmart-adata-c906-16-gb-usb-2-0-chernyi', {'price': 99.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-ii-i-series-8-gb-usb-2-0-chernyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-adata-c008-16-gb-usb-2-0-belyi-sinii', {'price': 99.0, 'available': False}),
                           ('foxmart-apacer-ah117-32-gb-usb-2-0-metal-serebristyi',
                            {'price': 199.0, 'available': False}),
                           ('foxmart-adata-uv220-8-gb-usb-2-0-turquoise-rozovyi', {'price': 89.0, 'available': False}),
                           ('foxmart-team-group-s112-8-gb-usb-2-0-chernyi', {'price': 79.0, 'available': False}),
                           (
                           'foxmart-adata-uv210-32-gb-usb-2-0-metal-serebristyi', {'price': 209.0, 'available': False}),
                           ('foxmart-silicon-power-helios-101-8-gb-usb-2-0-apple-zelionyi',
                            {'price': 89.0, 'available': False}),
                           ('foxmart-silicon-power-touch-t30-8-gb-usb-2-0-rubber-sinii',
                            {'price': 99.0, 'available': False}),
                           ('foxmart-apacer-ah355-64-gb-usb-3-0-chernyi', {'price': 259.0, 'available': False}),
                           ('foxmart-leef-ibridge-leef-ibridge-3-0-64-gb-usb-3-0-chernyi',
                            {'price': 999.0, 'available': False}),
                           ('foxmart-transcend-jetflash-310-8-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-adata-uv220-8-gb-usb-2-0-sinii-chernyi', {'price': 89.0, 'available': False}),
                           ('foxmart-silicon-power-t02-16-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           (
                           'foxmart-transcend-jetflash-700-8-gb-usb-3-0-chernyi', {'price': 139.0, 'available': False}),
                           ('foxmart-apacer-ah359-32-gb-usb-3-1-chernyi-sinii', {'price': 179.0, 'available': False}),
                           ('foxmart-apacer-ah23b-32-gb-usb-2-0-matte-metal-shell-chernyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah336-8-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-880-32-gb-usb-3-0-metal-serebristyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah336-16-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-pqi-u275l-8-gb-usb-2-0-belyi', {'price': 89.0, 'available': False}),
                           ('foxmart-goldkey-usb-flash-16-gb-chernyi-zolotoi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetdrive-go-300-32-gb-usb-3-1-serebristyi',
                            {'price': 799.0, 'available': False}),
                           ('foxmart-adata-uv320-16-gb-usb-3-0-zelionyi-belyi', {'price': 0.0, 'available': False}),
                           ('foxmart-adata-uv100-8-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u05-8-gb-usb-2-0-peach-zheltyi',
                            {'price': 99.0, 'available': False}),
                           ('foxmart-silicon-power-blaze-b05-16-gb-usb-3-0-peach-zheltyi',
                            {'price': 119.0, 'available': False}),
                           ('foxmart-adata-uv130-8-gb-usb-2-0-zinc-alloy-zolotoi', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-t835-16-gb-usb-2-0-sinii', {'price': 119.0, 'available': False}),
                           ('foxmart-transcend-jetflash-340-16-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-510-8-gb-usb-2-0-serebristyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u06-16-gb-usb-2-0-rozovyi',
                            {'price': 119.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u06-8-gb-usb-2-0-rozovyi',
                            {'price': 99.0, 'available': False}),
                           (
                           'foxmart-adata-s102-pro-16-gb-usb-3-0-titanium-seryi', {'price': 149.0, 'available': False}),
                           ('foxmart-transcend-jetflash-710s-16-gb-usb-3-0-serebristyi',
                            {'price': 259.0, 'available': False}),
                           ('foxmart-silicon-power-jewel-j01-16-gb-usb-3-0-metal-krasnyi',
                            {'price': 159.0, 'available': False}),
                           ('foxmart-apacer-ah357-16-gb-usb-3-1-ocean-sinii', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-820-8-gb-usb-3-0-zolotoi', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-ii-i-series-8-gb-usb-2-0-silver',
                            {'price': 0.0, 'available': False}),
                           (
                           'foxmart-transcend-jetflash-320-8-gb-usb-2-0-chernyi', {'price': 169.0, 'available': False}),
                           ('foxmart-apacer-ah322-16-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah23b-8-gb-usb-2-0-matte-metal-shell-chernyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah115-32-gb-usb-2-0-serebristyi', {'price': 199.0, 'available': False}),
                           ('foxmart-apacer-ah336-32-gb-usb-2-0-belyi', {'price': 0.0, 'available': False}),
                           ('foxmart-adata-uv320-16-gb-usb-3-0-sinii-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u05-16-gb-usb-2-0-peach-zheltyi',
                            {'price': 119.0, 'available': False}),
                           ('foxmart-silicon-power-helios-101-8-gb-usb-2-0-ocean-sinii',
                            {'price': 89.0, 'available': False}),
                           ('foxmart-apacer-ah336-32-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           (
                           'foxmart-transcend-jetflash-560-8-gb-usb-2-0-chernyi', {'price': 109.0, 'available': False}),
                           (
                           'foxmart-adata-uv310-16-gb-usb-3-1-metal-serebristyi', {'price': 169.0, 'available': False}),
                           ('foxmart-adata-uv210-8-gb-usb-2-0-metal-serebristyi', {'price': 119.0, 'available': False}),
                           ('foxmart-silicon-power-mobile-c80-64-gb-usb-3-1-serebristyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-blaze-b05-16-gb-usb-3-0-deep-sinii',
                            {'price': 119.0, 'available': False}),
                           ('foxmart-transcend-jetflash-520-8-gb-usb-2-0-metal-serebristyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-520-8-gb-usb-2-0-metal-zolotoi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-adata-c008-32-gb-usb-2-0-belyi-sinii', {'price': 179.0, 'available': False}),
                           ('foxmart-apacer-ah334-16-gb-usb-2-0-starry-blue-chernyi',
                            {'price': 129.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u05-16-gb-usb-2-0-deep-sinii',
                            {'price': 119.0, 'available': False}),
                           ('foxmart-transcend-jetflash-380-32-gb-usb-2-0-serebristyi',
                            {'price': 0.0, 'available': False}), (
                               'foxmart-silicon-power-marvel-m50-32-gb-usb-3-0-champagne-zolotoi',
                               {'price': 199.0, 'available': False}),
                           ('foxmart-adata-uv240-8-gb-usb-2-0-krasnyi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetdrive-go-300-64-gb-usb-3-1-chernyi',
                            {'price': 899.0, 'available': False}),
                           ('foxmart-adata-c906-8-gb-usb-2-0-belyi', {'price': 109.0, 'available': False}),
                           ('foxmart-adata-uv220-16-gb-usb-2-0-navy-sinii', {'price': 119.0, 'available': False}),
                           ('foxmart-goodram-ucl3-cl-ck-8-gb-usb-3-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah359-16-gb-usb-3-1-chernyi-sinii', {'price': 159.0, 'available': False}),
                           ('foxmart-apacer-ah116-32-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u31-8-gb-usb-3-0-zheltyi',
                            {'price': 99.0, 'available': False}),
                           ('foxmart-adata-uv130-32-gb-usb-2-0-zinc-alloy-zolotoi', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-mobile-c80-32-gb-usb-3-1-serebristyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-380-16-gb-usb-2-0-serebristyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-790-128-gb-usb-3-0-chernyi',
                            {'price': 569.0, 'available': False}),
                           ('foxmart-apacer-ah356-32-gb-usb-3-1-chernyi-sinii', {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah23b-64-gb-usb-2-0-matte-metal-shell-chernyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-jewel-j10-16-gb-usb-3-0-serebristyi',
                            {'price': 159.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u03-16-gb-usb-2-0-belyi', {'price': 0.0, 'available': False}),
                           (
                               'foxmart-samsung-bar-plus-muf-32be3-apc-128-gb-usb-3-1-metal-chernyi',
                               {'price': 599.0, 'available': False}),
                           ('foxmart-transcend-jetdrive-go-500-32-gb-usb-3-1-metal-zolotoi',
                            {'price': 839.0, 'available': False}),
                           ('foxmart-adata-c008-16-gb-usb-2-0-chernyi-krasnyi', {'price': 99.0, 'available': False}),
                           (
                           'foxmart-adata-uv210-16-gb-usb-2-0-metal-serebristyi', {'price': 129.0, 'available': False}),
                           ('foxmart-apacer-ah326-16-gb-usb-2-0-belyi', {'price': 99.0, 'available': False}),
                           ('foxmart-samsung-bar-plus-muf-32be3-apc-128-gb-serebristyi',
                            {'price': 699.0, 'available': False}),
                           ('foxmart-apacer-ah15a-16-gb-usb-3-1-dark-metal-seryi', {'price': 0.0, 'available': False}),
                           (
                               'foxmart-transcend-jetdrive-go-500-64-gb-usb-3-1-metal-serebristyi',
                               {'price': 999.0, 'available': False}),
                           ('foxmart-kingmax-ed-01-32-gb-usb-3-0-chernyi', {'price': 179.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u05-8-gb-usb-2-0-chernyi',
                            {'price': 99.0, 'available': False}),
                           ('foxmart-transcend-jetflash-520-16-gb-usb-2-0-metal-serebristyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-380-16-gb-usb-2-0-zolotoi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-750-64-gb-usb-2-0-chernyi',
                            {'price': 599.0, 'available': False}),
                           ('foxmart-adata-uv220-16-gb-usb-2-0-sinii-chernyi', {'price': 119.0, 'available': False}),
                           ('foxmart-adata-c008-8-gb-usb-2-0-belyi-sinii', {'price': 89.0, 'available': False}),
                           ('foxmart-apacer-ah118-32-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-kingmax-pd-02-16-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u31-8-gb-usb-3-0-krasnyi',
                            {'price': 99.0, 'available': False}),
                           ('foxmart-transcend-jetflash-810-8-gb-usb-3-0-oranzhevyi-chernyi',
                            {'price': 199.0, 'available': False}),
                           ('foxmart-leef-ibridge-leef-ibridge-3-0-32-gb-usb-3-0-chernyi',
                            {'price': 699.0, 'available': False}),
                           ('foxmart-apacer-ah322-8-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah155-16-gb-usb-3-1-sinii-serebristyi', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-marvel-m50-8-gb-usb-3-0-aqua-sinii',
                            {'price': 99.0, 'available': False}),
                           (
                           'foxmart-adata-s102-pro-16-gb-usb-3-0-titanium-sinii', {'price': 149.0, 'available': False}),
                           ('foxmart-adata-uv320-32-gb-usb-3-0-belyi-zelionyi', {'price': 0.0, 'available': False}),
                           ('foxmart-adata-c008-32-gb-usb-2-0-chernyi-krasnyi', {'price': 179.0, 'available': False}),
                           ('foxmart-apacer-ah356-16-gb-usb-3-1-chernyi-sinii', {'price': 0.0, 'available': False}),
                           ('foxmart-adata-uv100-8-gb-usb-2-0-krasnyi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-310-16-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u03-16-gb-usb-2-0-chernyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-380-32-gb-usb-2-0-zolotoi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-220-16-gb-usb-2-0-zelionyi-chernyi',
                            {'price': 199.0, 'available': False}),
                           (
                           'foxmart-apacer-ah156-32-gb-usb-3-1-dark-metal-seryi', {'price': 299.0, 'available': False}),
                           ('foxmart-transcend-jetflash-520-32-gb-usb-2-0-metal-serebristyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-510-32-gb-usb-2-0-metal-serebristyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah111-16-gb-usb-2-0-crystal-seryi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-890-16-gb-usb-3-1-metal-serebristyi',
                            {'price': 299.0, 'available': False}),
                           ('foxmart-transcend-jetflash-520-16-gb-usb-2-0-metal-zolotoi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-510-16-gb-usb-2-0-metal-zolotoi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-kingmax-ud-05-32-gb-usb-2-0-seryi', {'price': 179.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u05-16-gb-usb-2-0-chernyi',
                            {'price': 119.0, 'available': False}),
                           ('foxmart-silicon-power-marvel-m50-128-gb-usb-3-0-aqua-sinii',
                            {'price': 699.0, 'available': False}),
                           ('foxmart-transcend-jetflash-590-4-gb-usb-2-0-chernyi', {'price': 99.0, 'available': False}),
                           ('foxmart-transcend-jetflash-510-8-gb-usb-2-0-zolotoi', {'price': 0.0, 'available': False}),
                           (
                           'foxmart-adata-uv310-32-gb-usb-3-1-metal-serebristyi', {'price': 349.0, 'available': False}),
                           ('foxmart-goodram-uts3-twister-32-gb-usb-3-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-360-16-gb-usb-2-0-chernyi',
                            {'price': 139.0, 'available': False}),
                           ('foxmart-transcend-jetflash-380-8-gb-usb-2-0-zolotoi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-880-64-gb-usb-3-0-metal-serebristyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-340-8-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-adata-uv130-16-gb-usb-2-0-zinc-alloy-zolotoi', {'price': 0.0, 'available': False}),
                           ('foxmart-adata-c906-32-gb-usb-2-0-chernyi', {'price': 179.0, 'available': False}),
                           ('foxmart-adata-uv128-16-gb-usb-3-0-chernyi', {'price': 0.0, 'available': False}),
                           (
                           'foxmart-transcend-jetflash-600-8-gb-usb-2-0-chernyi', {'price': 149.0, 'available': False}),
                           ('foxmart-transcend-jetflash-510-32-gb-usb-2-0-metal-zolotoi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u06-16-gb-usb-2-0-sinii',
                            {'price': 119.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u06-8-gb-usb-2-0-sinii', {'price': 99.0, 'available': False}),
                           ('foxmart-adata-uv320-32-gb-usb-3-0-sinii-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-300-32-gb-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-340-32-gb-usb-2-0-chernyi-krasnyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-520-32-gb-usb-2-0-metal-zolotoi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah336-16-gb-usb-2-0-belyi', {'price': 0.0, 'available': False}),
                           ('foxmart-adata-uv250-16-gb-usb-2-0-metal-serebristyi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-350-64-gb-usb-2-0-chernyi',
                            {'price': 299.0, 'available': False}),
                           (
                           'foxmart-transcend-jetflash-790-8-gb-usb-3-0-chernyi', {'price': 139.0, 'available': False}),
                           ('foxmart-transcend-jetflash-320-32-gb-usb-2-0-chernyi',
                            {'price': 229.0, 'available': False}),
                           ('foxmart-adata-c906-8-gb-usb-2-0-chernyi', {'price': 109.0, 'available': False}),
                           ('foxmart-transcend-jetflash-730-8-gb-usb-3-0-belyi', {'price': 139.0, 'available': False}),
                           ('foxmart-apacer-ah116-16-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah23b-16-gb-usb-2-0-matte-metal-shell-chernyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-310-32-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u31-16-gb-usb-3-0-krasnyi',
                            {'price': 119.0, 'available': False}),
                           ('foxmart-transcend-jetflash-820-32-gb-usb-3-0-metal-zolotoi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-goodram-ucl3-cl-ck-16-gb-usb-3-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah112-32-gb-usb-2-0-krasnyi-serebristyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-firma-f80-16-gb-usb-2-0-serebristyi',
                            {'price': 149.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u05-8-gb-usb-2-0-deep-sinii',
                            {'price': 99.0, 'available': False}),
                           (
                           'foxmart-transcend-jetflash-590-8-gb-usb-2-0-chernyi', {'price': 139.0, 'available': False}),
                           ('foxmart-goodram-ucl3-cl-ck-64-gb-usb-3-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-510-16-gb-usb-2-0-metal-serebristyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah333-8-gb-usb-2-0-chernyi', {'price': 109.0, 'available': False}),
                           ('foxmart-transcend-jetdrive-go-300-32-gb-usb-3-1-chernyi',
                            {'price': 279.0, 'available': False}),
                           ('foxmart-apacer-ah111-8-gb-usb-2-0-crystal-seryi', {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah158-16-gb-usb-3-1-dark-metal-seryi', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-helios-101-16-gb-usb-2-0-apple-zelionyi',
                            {'price': 119.0, 'available': False}),
                           ('foxmart-apacer-ah322-32-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah111-8-gb-usb-2-0-seryi-sinii', {'price': 0.0, 'available': False}), (
                               'foxmart-silicon-power-ultima-ii-i-series-16-gb-usb-2-0-serebristyi',
                               {'price': 0.0, 'available': False}),
                           ('foxmart-adata-uv240-8-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-adata-uv240-32-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-590-32-gb-usb-2-0-chernyi',
                            {'price': 249.0, 'available': False}),
                           (
                           'foxmart-apacer-ah112-8-gb-usb-2-0-krasnyi-serebristyi', {'price': 0.0, 'available': False}),
                           ('foxmart-adata-c906-32-gb-usb-2-0-belyi', {'price': 179.0, 'available': False}),
                           ('foxmart-transcend-jetflash-730-16-gb-usb-3-0-belyi', {'price': 179.0, 'available': False}),
                           ('foxmart-adata-uv131-16-gb-usb-3-0-zinc-alloy-seryi', {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah355-16-gb-usb-3-0-chernyi', {'price': 159.0, 'available': False}),
                           ('foxmart-apacer-ah355-32-gb-usb-3-0-chernyi', {'price': 179.0, 'available': False}),
                           ('foxmart-transcend-jetflash-300-8-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           (
                           'foxmart-silicon-power-mobile-c80-16-gb-usb-3-1-silver', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-380-8-gb-usb-2-0-serebristyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-goodram-uts3-twister-16-gb-usb-3-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u06-32-gb-usb-2-0-rozovyi',
                            {'price': 179.0, 'available': False}),
                           ('foxmart-adata-c906-16-gb-usb-2-0-belyi', {'price': 79.0, 'available': False}),
                           ('foxmart-adata-uv240-16-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-t835-8-gb-usb-2-0-iron-seryi', {'price': 149.0, 'available': False}),
                           ('foxmart-silicon-power-t06-16-gb-usb-2-0-chernyi', {'price': 119.0, 'available': False}),
                           ('foxmart-silicon-power-jewel-j06-16-gb-usb-3-0-deep-sinii',
                            {'price': 159.0, 'available': False}),
                           ('foxmart-transcend-jetflash-330-8-gb-usb-2-0-belyi', {'price': 99.0, 'available': False}),
                           ('foxmart-silicon-power-helios-101-16-gb-usb-2-0-ocean-sinii',
                            {'price': 119.0, 'available': False}),
                           ('foxmart-adata-ud310-8-gb-usb-2-0-chernyi', {'price': 109.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-ii-i-series-16-gb-usb-2-0-chernyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-adata-uv131-32-gb-usb-3-0-zinc-alloy-seryi', {'price': 0.0, 'available': False}),
                           (
                           'foxmart-apacer-ah156-16-gb-usb-3-1-dark-metal-seryi', {'price': 199.0, 'available': False}),
                           ('foxmart-transcend-jetflash-710g-16-gb-usb-3-1-metal-zolotoi',
                            {'price': 199.0, 'available': False}),
                           (
                           'foxmart-transcend-jetflash-760-8-gb-usb-3-0-chernyi', {'price': 109.0, 'available': False}),
                           ('foxmart-adata-ud310-16-gb-usb-2-0-chernyi', {'price': 129.0, 'available': False}),
                           ('foxmart-goodram-uts3-twister-8-gb-usb-3-0-black', {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah111-16-gb-usb-2-0-seryi-sinii', {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah112-16-gb-usb-2-0-krasnyi-serebristyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-370-8-gb-usb-2-0-belyi', {'price': 149.0, 'available': False}),
                           ('foxmart-transcend-jetflash-590-8-gb-usb-2-0-white', {'price': 139.0, 'available': False}),
                           (
                               'foxmart-usams-aluminum-alloy-high-speed-64-gb-usb-2-0-serebristyi',
                               {'price': 199.0, 'available': False}), (
                               'foxmart-usams-aluminum-alloy-high-speed-32-gb-usb-2-0-serebristyi',
                               {'price': 179.0, 'available': False}), (
                               'foxmart-usams-aluminum-alloy-high-speed-16-gb-usb-2-0-serebristyi',
                               {'price': 139.0, 'available': False}),
                           ('foxmart-apacer-ah333-64-gb-usb-2-0-chernyi', {'price': 339.0, 'available': False}),
                           ('foxmart-usams-aluminum-alloy-high-speed-8-gb-usb-2-0-serebristyi',
                            {'price': 89.0, 'available': False}),
                           ('foxmart-transcend-jetflash-600-16-gb-usb-2-0-chernyi',
                            {'price': 259.0, 'available': False}),
                           ('foxmart-kingmax-pd-02-4-gb-usb-2-0-black', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-t01-4-gb-usb-2-0-metal-serebristyi',
                            {'price': 129.0, 'available': False}),
                           ('foxmart-samsung-duo-plus-128-gb-usb-3-1-chernyi-seryi',
                            {'price': 789.0, 'available': False}),
                           ('foxmart-transcend-jetdrive-go-300-64-gb-usb-3-1-serebristyi',
                            {'price': 899.0, 'available': False}),
                           (
                           'foxmart-transcend-jetflash-710s-8-gb-usb-3-0-silver', {'price': 159.0, 'available': False}),
                           ('foxmart-transcend-v85-16-gb-usb-2-0-serebristyi', {'price': 219.0, 'available': False}),
                           ('foxmart-silicon-power-t02-16-gb-usb-2-0-oranzhevyi', {'price': 0.0, 'available': False}),
                           ('foxmart-goodram-uts3-twister-64-gb-usb-3-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-jewel-j05-8-gb-usb-3-0-chernyi',
                            {'price': 159.0, 'available': False}),
                           ('foxmart-silicon-power-luxmini-322-16-gb-usb-2-0-chernyi',
                            {'price': 179.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u05-4-gb-usb-2-0-chernyi',
                            {'price': 129.0, 'available': False}),
                           ('foxmart-adata-uv130-8-gb-usb-2-0-zinc-alloy-serebristyi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-kingston-data-travel-se9-g2-32-gb-usb-3-0-serebristyi',
                            {'price': 179.0, 'available': False}),
                           ('foxmart-silicon-power-luxmini-720-32-gb-usb-2-0-deep-sinii',
                            {'price': 399.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u05-32-gb-usb-2-0-chernyi',
                            {'price': 379.0, 'available': False}),
                           ('foxmart-silicon-power-jewel-j80-8-gb-usb-3-0-titanium-seryi',
                            {'price': 149.0, 'available': False}),
                           (
                           'foxmart-silicon-power-blaze-b06-16-gb-usb-3-0-belyi', {'price': 199.0, 'available': False}),
                           (
                           'foxmart-silicon-power-t835-16-gb-usb-2-0-iron-seryi', {'price': 179.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u05-4-gb-usb-2-0-deep-sinii',
                            {'price': 129.0, 'available': False}),
                           ('foxmart-transcend-jetflash-500-64-gb-usb-3-1-chernyi',
                            {'price': 649.0, 'available': False}),
                           ('foxmart-silicon-power-luxmini-710-16-gb-usb-2-0-serebristyi',
                            {'price': 179.0, 'available': False}),
                           ('foxmart-silicon-power-luxmini-720-32-gb-usb-2-0-peach-zheltyi',
                            {'price': 399.0, 'available': False}),
                           ('foxmart-silicon-power-b10-8-gb-usb-3-0-chernyi', {'price': 139.0, 'available': False}),
                           ('foxmart-silicon-power-t06-8-gb-usb-2-0-chernyi', {'price': 129.0, 'available': False}),
                           ('foxmart-pqi-u275l-16-gb-usb-2-0-chernyi', {'price': 239.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-ii-i-series-4-gb-usb-2-0-silver',
                            {'price': 0.0, 'available': False}),
                           (
                           'foxmart-silicon-power-ultima-u06-4-gb-usb-2-0-sinii', {'price': 129.0, 'available': False}),
                           (
                           'foxmart-transcend-jetflash-560-4-gb-usb-2-0-chernyi', {'price': 129.0, 'available': False}),
                           ('foxmart-silicon-power-t02-16-gb-usb-2-0-green', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-t01-16-gb-usb-2-0-chernyi', {'price': 179.0, 'available': False}),
                           ('foxmart-silicon-power-t02-4-gb-usb-2-0-yellow', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u30-8-gb-usb-2-0-diamond-krasnyi',
                            {'price': 169.0, 'available': False}),
                           ('foxmart-silicon-power-luxmini-720-8-gb-usb-2-0-rozovyi',
                            {'price': 99.0, 'available': False}),
                           ('foxmart-silicon-power-jewel-j01-32-gb-usb-3-0-metal-krasnyi',
                            {'price': 349.0, 'available': False}),
                           ('foxmart-silicon-power-jewel-j08-8-gb-usb-3-0-krasnyi',
                            {'price': 139.0, 'available': False}),
                           ('foxmart-silicon-power-marvel-m50-16-gb-usb-3-0-aqua-sinii',
                            {'price': 149.0, 'available': False}),
                           ('foxmart-silicon-power-helios-101-4-gb-usb-2-0-apple-zelionyi',
                            {'price': 129.0, 'available': False}),
                           ('foxmart-silicon-power-touch-t07-8-gb-usb-2-0-rozovyi',
                            {'price': 129.0, 'available': False}),
                           (
                           'foxmart-transcend-jetflash-500-8-gb-usb-3-1-chernyi', {'price': 129.0, 'available': False}),
                           ('foxmart-adata-ud310-16-gb-usb-2-0-krasnyi', {'price': 129.0, 'available': False}),
                           ('foxmart-silicon-power-blaze-b05-16-gb-usb-3-0-chernyi',
                            {'price': 159.0, 'available': False}),
                           ('foxmart-silicon-power-t850-16-gb-usb-2-0-titanium-seryi',
                            {'price': 259.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u03-32-gb-usb-2-0-white', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u03-8-gb-usb-2-0-white', {'price': 0.0, 'available': False}),
                           (
                           'foxmart-transcend-jetflash-600-4-gb-usb-2-0-chernyi', {'price': 149.0, 'available': False}),
                           (
                           'foxmart-silicon-power-t01-16-gb-usb-2-0-serebristyi', {'price': 179.0, 'available': False}),
                           ('foxmart-silicon-power-t830-8-gb-usb-2-0-metal-serebristyi',
                            {'price': 79.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u03-4-gb-usb-2-0-black', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-600-64-gb-usb-2-0-chernyi',
                            {'price': 659.0, 'available': False}),
                           ('foxmart-transcend-jetflash-370-4-gb-belyi', {'price': 79.0, 'available': False}),
                           ('foxmart-transcend-jetflash-780-32-gb-usb-3-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-810-16-gb-usb-3-0-krasnyi-chernyi',
                            {'price': 219.0, 'available': False}),
                           ('foxmart-silicon-power-blaze-b02-32-gb-usb-3-0-chernyi',
                            {'price': 379.0, 'available': False}),
                           ('foxmart-silicon-power-luxmini-710-4-gb-usb-2-0-serebristyi',
                            {'price': 116.0, 'available': False}),
                           ('foxmart-silicon-power-luxmini-720-16-gb-usb-2-0-zolotoi',
                            {'price': 199.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u03-8-gb-usb-2-0-black', {'price': 0.0, 'available': False}),
                           (
                           'foxmart-transcend-jetflash-500-4-gb-usb-3-1-chernyi', {'price': 109.0, 'available': False}),
                           ('foxmart-transcend-jetflash-320-16-gb-usb-2-0-chernyi',
                            {'price': 199.0, 'available': False}),
                           ('foxmart-silicon-power-t01-8-gb-usb-2-0-chernyi', {'price': 139.0, 'available': False}),
                           ('foxmart-silicon-power-t830-16-gb-usb-2-0-serebristyi',
                            {'price': 159.0, 'available': False}),
                           ('foxmart-silicon-power-t835-4-gb-usb-2-0-iron-seryi', {'price': 129.0, 'available': False}),
                           (
                           'foxmart-silicon-power-t851-8-gb-usb-2-0-serebristyi', {'price': 149.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u03-4-gb-usb-2-0-white', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u06-32-gb-usb-2-0-sinii',
                            {'price': 379.0, 'available': False}),
                           ('foxmart-silicon-power-jewel-j07-8-gb-usb-3-0-aqua-sinii',
                            {'price': 159.0, 'available': False}),
                           ('foxmart-transcend-jetflash-500-32-gb-usb-3-1-chernyi',
                            {'price': 349.0, 'available': False}),
                           ('foxmart-transcend-v90-8-gb-usb-2-0-serebristyi', {'price': 179.0, 'available': False}),
                           ('foxmart-apacer-ah118-8-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah-521-4-gb-usb-2-0-chernyi', {'price': 159.0, 'available': False}),
                           ('foxmart-silicon-power-blaze-b05-32-gb-usb-3-0-chernyi',
                            {'price': 349.0, 'available': False}),
                           ('foxmart-silicon-power-luxmini-720-8-gb-usb-2-0-deep-sinii',
                            {'price': 159.0, 'available': False}),
                           ('foxmart-silicon-power-t836-8-gb-usb-2-0-zolotoi', {'price': 129.0, 'available': False}),
                           ('foxmart-silicon-power-blaze-b20-8-gb-usb-3-0-diamond-chernyi',
                            {'price': 139.0, 'available': False}),
                           ('foxmart-transcend-jetflash-300-4-gb-usb-2-0-black', {'price': 0.0, 'available': False}),
                           ('foxmart-pqi-u819v-8-gb-usb-2-0-chernyi', {'price': 179.0, 'available': False}),
                           ('foxmart-silicon-power-firma-f80-32-gb-usb-2-0-serebristyi',
                            {'price': 349.0, 'available': False}),
                           ('foxmart-silicon-power-firma-f80-8-gb-usb-2-0-serebristyi',
                            {'price': 169.0, 'available': False}),
                           ('foxmart-silicon-power-t02-4-gb-usb-2-0-green', {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-500-16-gb-usb-3-1-chernyi',
                            {'price': 139.0, 'available': False}),
                           ('foxmart-transcend-jetflash-770-32-gb-usb-3-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-kingmax-u-drive-16-gb-usb-2-0-sinii', {'price': 269.0, 'available': False}),
                           ('foxmart-silicon-power-luxmini-720-32-gb-usb-2-0-zolotoi',
                            {'price': 399.0, 'available': False}),
                           ('foxmart-silicon-power-t02-8-gb-usb-2-0-black', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-t851-16-gb-usb-2-0-serebristyi',
                            {'price': 259.0, 'available': False}),
                           ('foxmart-silicon-power-jewel-j01-8-gb-usb-3-0-metal-krasnyi',
                            {'price': 139.0, 'available': False}),
                           ('foxmart-silicon-power-touch-t08-8-gb-usb-2-0-belyi', {'price': 139.0, 'available': False}),
                           ('foxmart-transcend-jetflash-810-32-gb-usb-3-0-chernyi-sinii',
                            {'price': 289.0, 'available': False}),
                           ('foxmart-kingston-data-travel-se9-g2-16-gb-usb-3-0-serebristyi',
                            {'price': 149.0, 'available': False}),
                           ('foxmart-silicon-power-blaze-b02-8-gb-usb-3-0-chernyi',
                            {'price': 139.0, 'available': False}),
                           ('foxmart-kingmax-ud-02-16-gb-usb-2-0-krasnyi', {'price': 149.0, 'available': False}),
                           ('foxmart-silicon-power-jewel-j10-64-gb-usb-3-0-serebristyi',
                            {'price': 799.0, 'available': False}),
                           ('foxmart-silicon-power-t01-32-gb-usb-2-0-chernyi', {'price': 379.0, 'available': False}),
                           ('foxmart-silicon-power-t03-8-gb-usb-2-0-metal-serebristyi',
                            {'price': 149.0, 'available': False}),
                           (
                           'foxmart-silicon-power-t835-32-gb-usb-2-0-iron-seryi', {'price': 379.0, 'available': False}),
                           (
                           'foxmart-transcend-jetflash-360-4-gb-usb-2-0-chernyi', {'price': 149.0, 'available': False}),
                           ('foxmart-transcend-jetflash-600-32-gb-usb-2-0-chernyi',
                            {'price': 319.0, 'available': False}),
                           ('foxmart-transcend-jetflash-820-16-gb-usb-3-0-metal-zolotoi',
                            {'price': 0.0, 'available': False}),
                           ('foxmart-transcend-jetflash-330-16-gb-usb-2-0-belyi', {'price': 139.0, 'available': False}),
                           ('foxmart-apacer-ah222-4-gb-usb-2-0-sinii-chernyi', {'price': 0.0, 'available': False}),
                           (
                           'foxmart-silicon-power-t03-16-gb-usb-2-0-serebristyi', {'price': 119.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u03-32-gb-usb-2-0-black', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-helios-101-4-gb-usb-2-0-ocean-sinii',
                            {'price': 129.0, 'available': False}),
                           ('foxmart-silicon-power-touch-t07-8-gb-usb-2-0-sinii', {'price': 129.0, 'available': False}),
                           ('foxmart-silicon-power-touch-t08-8-gb-usb-2-0-rozovyi',
                            {'price': 139.0, 'available': False}),
                           ('foxmart-transcend-jetflash-360-32-gb-usb-2-0-chernyi',
                            {'price': 189.0, 'available': False}),
                           (
                           'foxmart-transcend-jetflash-360-8-gb-usb-2-0-chernyi', {'price': 149.0, 'available': False}),
                           ('foxmart-transcend-jetflash-760-32-gb-usb-3-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-apacer-ah116-8-gb-usb-2-0-chernyi', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-touch-t20-8-gb-usb-2-0-metal-zolotoi',
                            {'price': 139.0, 'available': False}),
                           ('foxmart-pqi-u275l-8-gb-usb-2-0-chernyi', {'price': 109.0, 'available': False}),
                           ('foxmart-silicon-power-t830-4-gb-usb-2-0-metal-serebristyi',
                            {'price': 129.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u06-4-gb-usb-2-0-rozovyi',
                            {'price': 129.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u31-16-gb-usb-3-0-zheltyi',
                            {'price': 119.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u31-4-gb-usb-3-0-zheltyi',
                            {'price': 129.0, 'available': False}),
                           ('foxmart-transcend-jetflash-t3-8-gb-usb-2-0-chernyi', {'price': 149.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-02-4-gb-usb-2-0-black', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-t850-8-gb-usb-2-0-zolotoi', {'price': 149.0, 'available': False}),
                           ('foxmart-silicon-power-t850-8-gb-usb-2-0-titanium-seryi',
                            {'price': 149.0, 'available': False}),
                           ('foxmart-silicon-power-t851-8-gb-usb-2-0-zolotoi', {'price': 149.0, 'available': False}),
                           ('foxmart-silicon-power-ultima-u31-4-gb-usb-3-0-krasnyi',
                            {'price': 129.0, 'available': False}),
                           ('foxmart-transcend-jetflash-200-16-gb-usb-2-0-chernyi',
                            {'price': 139.0, 'available': False}),
                           ('foxmart-transcend-jetflash-350-4-gb-usb-2-0-black', {'price': 79.0, 'available': False}),
                           ('foxmart-silicon-power-jewel-j10-8-gb-usb-3-0-serebristyi',
                            {'price': 149.0, 'available': False}),
                           ('foxmart-silicon-power-blaze-b05-32-gb-usb-3-0-deep-sinii',
                            {'price': 309.0, 'available': False}),
                           ('foxmart-silicon-power-luxmini-710-4-gb-usb-2-0-chernyi',
                            {'price': 116.0, 'available': False}),
                           ('foxmart-adata-uv100-8-gb-usb-2-0-sinii', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-jewel-j07-8-gb-usb-3-0-iron-seryi',
                            {'price': 159.0, 'available': False}),
                           ('foxmart-kingmax-ud-01-4-gb-usb-2-0-chernyi', {'price': 139.0, 'available': False}),
                           ('foxmart-silicon-power-jewel-j10-32-gb-usb-3-0-serebristyi',
                            {'price': 319.0, 'available': False}),
                           ('foxmart-silicon-power-t01-4-gb-usb-2-0-chernyi', {'price': 116.0, 'available': False}),
                           ('foxmart-silicon-power-t02-4-gb-usb-2-0-black', {'price': 0.0, 'available': False}),
                           ('foxmart-silicon-power-t01-8-gb-usb-2-0-metal-serebristyi',
                            {'price': 139.0, 'available': False}),
                           ('foxmart-silicon-power-jewel-j06-8-gb-usb-3-0-deep-sinii',
                            {'price': 139.0, 'available': False}),
                           ('foxmart-kingmax-snowman-edition-4-gb-usb-2-0-belyi', {'price': 139.0, 'available': False}),
                           ('foxmart-silicon-power-luxmini-720-8-gb-usb-2-0-zolotoi',
                            {'price': 159.0, 'available': False}),
                           ('foxmart-silicon-power-luxmini-720-8-gb-usb-2-0-peach-zheltyi',
                            {'price': 159.0, 'available': False}),
                           ('foxmart-silicon-power-marvel-m50-8-gb-usb-3-0-champagne-zolotoi',
                            {'price': 149.0, 'available': False}),
                           ('foxmart-apacer-ah353-64-gb-usb-2-0-zolotoi', {'price': 0.0, 'available': False}),
                           ('foxmart-kingmax-ed-01-16-gb-usb-3-0-chernyi', {'price': 319.0, 'available': False}),
                           ('foxmart-kingmax-ud-09-32-gb-usb-3-0-chernyi', {'price': 459.0, 'available': False}),
                           ('foxmart-silicon-power-blaze-b05-8-gb-usb-3-0-deep-sinii',
                            {'price': 139.0, 'available': False}),
                           ('foxmart-silicon-power-t03-32-gb-usb-2-0-metal-serebristyi',
                            {'price': 379.0, 'available': False}),
                           ('foxmart-transcend-v85-8-gb-usb-2-0-serebristyi', {'price': 189.0, 'available': False}),
                    ])]
